# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e6d456dcd741eb5c9ce18229c5da7b2de367c23cb0cd2cb97b3e992f0500cf1b33a21aa255da598c49a677fc7c2e941818f312b99c02f4ceff38056f018ab75

test:
  secret_key_base: ba9542a4ff98b3e07c39c7a68acb205fb9edf047a2f0bb080ec29538c7a3c8d9aff636080828881a2c15bafbec53e8870fe0b7fb2ab086ee13b7b5134e0b2632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
